Portafolio/Portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from panel import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portafolio/blog/urls.py
from django.urls import path
from .views import renderPost, postDetail

app_name = 'blog'

urlpatterns = [
     path('', renderPost, name='post'),
     # Recibe un parametro a la URL de tipo int
     path('<int:postID>', postDetail, name="postDetail")
]

Portafolio/blog/models.py
from django.db import models
import datetime
# Create your models here.
from django.db.models import CharField, TextField, DateField


class Post(models.Model):
    tittle = models.CharField(max_length=100)   # Se puede importar desde modelos
    description = TextField()     # O importando la clase en la parte superior
    image = models.ImageField(upload_to='blog/images/')
    date = DateField(datetime.date.today)

Portafolio/panel/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


# Create your models here.
class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=100)
    image = ImageField(upload_to='panel/images/')
    urlProyect = URLField(blank=True)

Portafolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post    # Importamos la base de datos
# Create your views here.


def renderPost(request):
    posts = Post.objects.all()  #Select chido
    return render(request, 'post.html', {'posts': posts})


def postDetail(request, postID):
    post = get_object_or_404(Post, pk=postID)
    return render(request, 'postDetail.html', {'post': post})

Portafolio/panel/views.py
from django.shortcuts import render
from .models import Project


# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

Portafolio/blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts %}
        <div class="p-3">
            <div class="card card-body bg-black">
                <div class="row">
                    <div class="col-3">
                        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                    </div>
                    <div class="col-9">
                        <h2>{{ post.tittle }}</h2>
                        <!-- Se imprime la descripcion |striptags, elimina las etiquetas|Imprime las 100 primeras letras -->
                        <p>{{ post.description|striptags|truncatechars:100}}</p>
                        <p>{{ post.date| date:'M d Y'}}</p>
                        <a href="{% url 'blog:postDetail' post.id %}" class="btn btn-primary">{{ post.tittle }}</a>

                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

Portafolio/blog/templates/postDetail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="text-center">
        <h2>{{ post.tittle }}</h2>
        <h3 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h3>
        <img src="{{ post.image.url }}" alt="{{ post.tittle}}" class="img-fluid">
        <div class="my-4">
            <p>{{ post.description|safe }}</p>
        </div>

    </div>
{% endblock %}

Portafolio/panel/templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <header class="row bg-black">
        <div class="col-md-4">
            <img src="{% static 'portafolio/PW_W.png' %}" alt="" height="450px">
        </div>
        <div class="col-md-8 my-auto">
            <h1>I am <strong>Wicho</strong> </h1>
            <h3>I'm Software Engineer</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur cupiditate ea eaque eum facilis
                minus optio, quidem. Delectus ex laborum molestias nam necessitatibus nihil nobis quas. Aliquam atque
                dignissimos ea eligendi et fugiat fugit illum iure, minima modi molestias nisi suscipit voluptatibus!
                Amet eveniet laudantium necessitatibus obcaecati officiis placeat reiciendis rem voluptates voluptatibus.
                Ab adipisci assumenda at atque beatae, consequatur distinctio dolores ea et, expedita fugiat in ipsum
                iste magni minus nam necessitatibus quam quia quis repellat suscipit tempora tempore temporibus voluptate,
                voluptatum? Dolor dolorum in iure laborum molestiae perferendis sed, totam veritatis. Aliquid blanditiis
                eos obcaecati temporibus veritatis? Dignissimos!</p>
            <a href="{% static 'portafolio/CV_MartinezSilva.pdf' %}" target="_blank" class="btn btn-primary btn-lg rounded-0 my-3">Download CV</a>
        </div>
    </header>

    <div class="row my-4 text-center">
        <h3>My Projects</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, necessitatibus!</p>

        {% for project in projects %}   <!-- For loop para recorrer un array de objetos -->
            <div class="col-md-4 p-4">
                <div class="card bg-black card-project">
                    <img src="{{ project.image.url }}" alt="{{ project.title }}" class="img-fluid" card-img-top>
                    <div class="card-body">
                        <h2>{{ project.title}} </h2> <!-- Sintaxis para imprimir un valor de python en html -->
                        <p>{{ project.description }}</p>

                        {% if project.urlProyect %}
                            <a href="{{ project.urlProyect }}" class="btn btn-light rounded-0 btn-sm"
                               target="_blank">{{ project.urlProyect }}</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Portafolio/panel/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Django Portafolio</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'main.css' %}">
    </head>
    <body class="text-light">
        {% include 'partials/_navbar.html' %}

        <div class="container p-4">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

Portafolio/panel/templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand fw-bold" href="/">Wicho0409</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:post' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portafolio/CV_MartinezSilva.pdf' %}" target="_blank">Download CV</a>
        </li>
      </ul>
    </div>
  </div>
</nav>